[project]
name = "slackbot-backend"
version = "0.1.0"
requires-python = ">=3.10"
description = "Slackbot backend (scaffold)"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.ruff]
line-length = 100
